### ISSUE TITLE
Potential bug in TLPS implementation 

### ISSUE THREAD

**Issue by achasol** [kelicht/dace#1]
Dear Kentaro Kanamori,

Great work on the DACE paper. I am working on a replication study to complete my undergraduate studies at Erasmus University. During my replication, I think I have found a potential bug in the TLPS implementation provided in this repo. I have included a reference to the section below. 

I believe the bug is caused by line 232 where an empty list is added to the cost array C_ in case a feature is fixed. 
However once the cost array C is flattened this empty list is removed, leaving C_ with a smaller size than the flat_pi vector. 
Sadly this dimension mismatch is not a problem for functions like lpDot or zip, since they simply truncate the longer array. 

https://github.com/kelicht/dace/blob/c6eba5c23d180be44876a39dbf970d63d6bd8c7c/utils.py#LL228C8-L236C114

The dimension mismatch can be observed by printing the shape of both the flattened Cost matrix (C_) and flat_pi. 

A way to fix the issue would be to change line 232 to: 
```python 
self.costs_.append([0 for _ in self.actions_[d] ] ) 
```
Since then the dimensionality of flat_pi and the flattened cost array C_ will match. Would love to hear your thoughts. 

Best regards,
Naim

**Comment by kelicht** [comment]
Dear Naim,

Thank you for your pointing out!
I have fixed the issue in utils.py so that the dimensionality of flat_pi equals to that of the flattened cost array C_.  
I hope it helps you. 

Sincerely,
Kentaro

**Comment by achasol** [comment]
Dear Kentaro,

Thanks for the swift course of action. 

All the best,
Naim
